---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3a","m2"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "small", "micro"]
      nodeClassRef:
        name: karpenter-default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 360h # 15 * 24h = 360h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: karpenter-default
spec:
  amiFamily: AL2 # Amazon Linux 2
  instanceProfile: "<add the instance profile>"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<cluster name>" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<cluster name>" # replace with your cluster name
  tags:
    Name: karpenter.sh/pool/default
