apiVersion: v1
kind: Service
metadata:
  name: flask-python-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
