apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-python-app
  labels: 
     app: flask-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-app-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-python-app
        image: ecr.amazonaws.com/flask-app:latest #Replace it with your ECR
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
